favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://localhost/PAFF2016/themes/PAFF/favicon.ico'
  use_default: true
schemas:
  bootstrap: 8000
  PAFF: 8000
logo:
  path: 'public://logo.png'
  url: ''
  use_default: false
table_responsive: '-1'
table: ''
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
cdn_provider: ''
